[build]
    [context.production]
        publish = 'dist/'
        command = 'npm run build'
    [context.staging]
        publish = 'dist/'
        command = 'npx nuxi generate'    

[[redirects]]
    from = "/*"
    to = "index.html"
    status = 200
